version: '3'

services:
  thrill_dash_lib:
    image: themattrix/tox
    volumes:
      - ../../:/source
    env_file:
      - ../../tests/.tests.env
    entrypoint: ../../source/docker/ci/run-tests.sh
